In [1]:
from __future__ import division
import time
from random import randint,random,choice
import numpy as np
from math import sqrt,exp,e
from playxo import newboard, play_game
from stratagies import stupidai, oneturnai
from neuralnet import *
import random
random.seed(13372)

In [2]:
coach = oneturnai()

for i in range(500):
    board = newboard()
    play_game(coach,stupidai,board)
for i in range(500):
    board = newboard()
    play_game(coach,oneturnai(),board)

moves = coach.trainingdata.values()
goal = [[1 if move == i else 0 for i in range(1,10)] for move in moves]
inputs = coach.trainingdata.keys()

In [3]:
hiddenwidth = 9
inwidth = 9*3
outwidth = 9

gens = 100
threshold = 0.01
popsize = 100
cut = 50

popu = [NNXO.newrandom(inwidth,hiddenwidth,outwidth) for i in range(popsize)]
xoevolve = EvolutionLearning(inputs,goal,popsize,cut,popu)

In [4]:
all_fittest = []
i = 0
clock0 = time.clock()

In [5]:
while True:
    xoevolve(gens,threshold)
    fittest =xoevolve.population[0]
    all_fittest.append(fittest)
    print i,
    print fittest.error,
    print fittest.maxdelta, 
    print 't: {}'.format(int(time.clock() - clock0)),
    stupidgames = [play_game( all_fittest[-1],stupidai,board) for j in range(10000)]
    print 'stupid losses: {}'.format(stupidgames.count(-2 ))
    if fittest.error < threshold:
        break
    i += gens

0 0.956591377009 0.112669964221 t: 35 stupid losses: 4116
100 0.929091337342 -0.967990458709 t: 74 stupid losses: 8535
200 0.907166572929 -0.610541036448 t: 113 stupid losses: 9684
300 0.900148494088 0.367317241996 t: 153 stupid losses: 9275
400 0.891603427697 0.600499009397 t: 192 stupid losses: 9878
500 0.886090690108 0.45795305717 t: 232 stupid losses: 9894
600 0.884100652941 -0.13716917685 t: 272 stupid losses: 9664
700 0.880068249141 -0.546454108691 t: 312 stupid losses: 9911
800 0.876997763323 0.312274342704 t: 353 stupid losses: 9894
900 0.875866820931 -0.390821249738 t: 392 stupid losses: 9888
1000 0.874794911695 -0.102055602473 t: 438 stupid losses: 9874
1100 0.874157764139 0.875887600225 t: 477 stupid losses: 9891
1200 0.872635713377 -0.347240474762 t: 516 stupid losses: 9681
1300 0.872294735461 0.31623499017 t: 554 stupid losses: 9681
1400 0.871565668971 0.815417773393 t: 592 stupid losses: 9672
1500 0.871054121598 0.660429188171 t: 631 stupid losses: 9904
1600 0.87105412159

KeyboardInterrupt: 

In [63]:
%prun xoevolve(gens,threshold)

In [84]:
fittest.maxdelta = 0.1
print i

37700


In [7]:
print time.clock()

2033.740554


In [19]:
calcs = fittest.calcout(0)
calcs = np.array(calcs)
xoevolve.goal = np.array(xoevolve.goal)

sums = [sum(calcs[l] * xoevolve.goal[l])/(sqrt(sum(calcs[l]**2)) * sqrt(sum(xoevolve.goal[l]**2))) for l in range(len(calcs))]
avgsum = sum(sums)/len(sums)
print avgsum
print

for l in range(len(calcs)):
    print calcs[l]
    print xoevolve.goal[l]
    print sum(calcs[l] * xoevolve.goal[l])/(sqrt(sum(calcs[l]**2)) * sqrt(sum(xoevolve.goal[l]**2)))
    print

0.463905653176

[ 0.          0.          0.056662    0.00780302  0.          0.
  0.18020604  0.          0.        ]
[0 0 0 0 0 0 1 0 0]
0.953141812486

[ 0.          0.          0.          0.          0.          0.
  0.53070454  0.          0.        ]
[0 0 1 0 0 0 0 0 0]
0.0

[ 0.          0.09308015  0.          0.          1.10574933  0.
  0.00281216  0.          0.        ]
[0 1 0 0 0 0 0 0 0]
0.0838814111647

[ 0.          0.09079077  0.17402485  0.04066344  0.48970109  0.
  0.04732756  0.          0.        ]
[0 0 0 0 1 0 0 0 0]
0.921787640799

[ 0.          0.08046175  0.          0.          0.80411793  0.
  0.02211139  0.          0.        ]
[1 0 0 0 0 0 0 0 0]
0.0

[ 0.          0.05153832  0.12686733  0.0876023   0.          0.
  0.08604902  0.          0.        ]
[1 0 0 0 0 0 0 0 0]
0.0

[ 0.          0.03980914  0.          0.          0.0015967   0.
  0.07192164  0.          0.18131234]
[0 0 0 0 0 0 1 0 0]
0.361263850221

[ 0.          0.02902302  0.09981766  0.114

In [91]:
print coach.trainingdata

{'\nx.o\nx.x\n.oo\n': 7, '\noo.\no.x\nxx.\n': 9, '\nx.x\nxoo\no..\n': 2, '\noo.\n.x.\n.x.\n': 3, '\n.oo\nxx.\n.ox\n': 6, '\nxoo\no.x\nxox\n': 5, '\n.x.\no.o\nx..\n': 5, '\no.x\n..x\nxoo\n': 5, '\n.xo\nxox\n.o.\n': 7, '\no.x\n..o\nx..\n': 5, '\noxx\nxo.\no..\n': 9, '\nxo.\noox\nx..\n': 8, '\nx..\n.o.\n.ox\n': 2, '\n..x\n.o.\n.xo\n': 1, '\no.x\n.ox\nox.\n': 9, '\noxx\n.o.\nxo.\n': 9, '\nxx.\noo.\n...\n': 3, '\nx..\nxxo\no.o\n': 3, '\n..o\n.ox\n..x\n': 7, '\nox.\n...\nx.o\n': 5, '\nxxo\no.x\no..\n': 5, '\noxx\nxoo\nox.\n': 9, '\noxx\n.o.\nox.\n': 4, '\n...\nxox\n.o.\n': 2, '\nxx.\no..\n.o.\n': 3, '\n..x\no..\nox.\n': 1, '\nox.\nxo.\n...\n': 9, '\nx.o\n...\nox.\n': 5, '\no..\n...\nxxo\n': 5, '\nxxo\no..\no.x\n': 5, '\no.x\nxo.\no.x\n': 6, '\noxo\nxo.\n.x.\n': 9, '\n...\no.o\nx.x\n': 8, '\nxo.\n.o.\n..x\n': 8, '\n.o.\n.xo\noxx\n': 1, '\n.x.\noo.\n.x.\n': 6, '\n.ox\nxoo\n..x\n': 8, '\no.x\nxo.\n...\n': 9, '\nx..\nx.o\n..o\n': 7, '\n..o\nx.x\noox\n': 5, '\n.xo\nox.\nx.o\n': 8, '\n..o\nx.o\n.x

In [92]:
print goal

[[0, 0, 0, 0, 0, 0, 1, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 1], [0, 1, 0, 0, 0, 0, 0, 0, 0], [0, 0, 1, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 1, 0, 0, 0], [0, 0, 0, 0, 1, 0, 0, 0, 0], [0, 0, 0, 0, 1, 0, 0, 0, 0], [0, 0, 0, 0, 1, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 1, 0, 0], [0, 0, 0, 0, 1, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 1], [0, 0, 0, 0, 0, 0, 0, 1, 0], [0, 1, 0, 0, 0, 0, 0, 0, 0], [1, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 1], [0, 0, 0, 0, 0, 0, 0, 0, 1], [0, 0, 1, 0, 0, 0, 0, 0, 0], [0, 0, 1, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 1, 0, 0], [0, 0, 0, 0, 1, 0, 0, 0, 0], [0, 0, 0, 0, 1, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 1], [0, 0, 0, 1, 0, 0, 0, 0, 0], [0, 1, 0, 0, 0, 0, 0, 0, 0], [0, 0, 1, 0, 0, 0, 0, 0, 0], [1, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 1], [0, 0, 0, 0, 1, 0, 0, 0, 0], [0, 0, 0, 0, 1, 0, 0, 0, 0], [0, 0, 0, 0, 1, 0, 0, 0, 0], [0, 0, 0, 0, 0, 1, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 1], [0, 0, 0, 0, 0, 0, 0, 1, 0], [0, 0, 0, 0, 0, 0, 0, 1, 0], [1, 0, 0, 0, 