In [65]:
from __future__ import division
from numpy.random import random, randint
from random import choice
import numpy as np
from numpy import dot, array
from symbolicai import *
from neuralnet2 import *
import oneturntestingequal as oneequal 
equalinputs = oneequal.inputs
equalgoal = oneequal.goal
import oneturntestingblock as oneblock
blockinputs = oneblock.inputs
blockgoal = oneblock.goal
import oneturntestingwin as onewin
wininputs = onewin.inputs
wingoal = onewin.goal
import QLearningtraining as qtrain
np.random.seed(1337)

In [2]:
a = XOQLearning()

In [3]:
%%time 
#Q-Learning, Reinforcement Learning.
for i in xrange(2000):
    a.learn(stupidai2,'x', multi=0.2)
    a.learn(stupidai2,'o', multi=0.2)
    
for i in xrange(100000):
    a.learn(oneturnai2(),'x', multi=0.2)
    
for i in xrange(100000):
    a.learn(oneturnai2(),'x', multi=1)
    
for i in xrange(100000):
    a.learn(oneturnai2(),'x', multi=5)
    
for i in xrange(100000):
    a.learn(oneturnai2(),'o', multi=0.2)
    
for i in xrange(100000):
    a.learn(oneturnai2(),'o', multi=1)
    
for i in xrange(100000):
    a.learn(oneturnai2(),'o', multi=5)

CPU times: user 3min 5s, sys: 863 ms, total: 3min 6s
Wall time: 3min 8s


In [4]:
print len(a.database)
a.multi = 50
oresults = [playgame(oneturnai2(),a,newboard())*-1 for i in xrange(500)]
xresults = [playgame(a,oneturnai2(),newboard()) for i in xrange(500)]
results = array(oresults+xresults)
print 'lose', np.sum(results==-1)
print 'draw', np.sum(results==0)
print 'win', np.sum(results==1)
print 'mistake', np.sum(results==-2)
results = array(xresults)
print 'xlose', np.sum(results==-1)
print 'xdraw', np.sum(results==0)
print 'xwin', np.sum(results==1)
print 'xmistake', np.sum(results==-2)
results = array(oresults)
print 'olose', np.sum(results==-1)
print 'odraw', np.sum(results==0)
print 'owin', np.sum(results==1)
print 'omistake', np.sum(results==-2)

4091
lose 31
draw 258
win 711
mistake 0
xlose 0
xdraw 17
xwin 483
xmistake 0
olose 31
odraw 241
owin 228
omistake 0


In [5]:
perceptron = XOPerceptron.initalize(27,9,activation=rectified_linear)
plearnfunc = GradeintDecent(equalinputs, equalgoal, perceptron)
gens = 1000
threshold = 0

In [6]:
%%time
#Perceptron, Supervised Learning.
equal = plearnfunc(gens, threshold)
print equal.error

0.137671626464
CPU times: user 4min 50s, sys: 8.06 s, total: 4min 58s
Wall time: 1min 18s


In [7]:
oresults = [playgame(oneturnai2(),equal,newboard())*-1 for i in xrange(500)]
xresults = [playgame(equal,oneturnai2(),newboard()) for i in xrange(500)]
results = array(oresults+xresults)
print 'lose', np.sum(results==-1)
print 'draw', np.sum(results==0)
print 'win', np.sum(results==1)
print 'mistake', np.sum(results==-2)

lose 365
draw 635
win 0
mistake 0


In [8]:
perceptron = XOPerceptron.initalize(27,9,activation=rectified_linear)
plearnfunc = GradeintDecent(blockinputs, blockgoal, perceptron)
gens = 1000
threshold = 0

In [9]:
%%time
#Perceptron, Supervised Learning.
block = plearnfunc(gens, threshold)
print block.error

0.227504766857
CPU times: user 4min 45s, sys: 6.63 s, total: 4min 52s
Wall time: 1min 15s


In [10]:
oresults = [playgame(oneturnai2(),block,newboard())*-1 for i in xrange(500)]
xresults = [playgame(block,oneturnai2(),newboard()) for i in xrange(500)]
results = array(oresults+xresults)
print 'lose', np.sum(results==-1)
print 'draw', np.sum(results==0)
print 'win', np.sum(results==1)
print 'mistake', np.sum(results==-2)

lose 344
draw 649
win 7
mistake 0


In [11]:
perceptron = XOPerceptron.initalize(27,9,activation=rectified_linear)
plearnfunc = GradeintDecent(wininputs, wingoal, perceptron)
gens = 1000
threshold = 0

In [12]:
%%time
#Perceptron, Supervised Learning.
win = plearnfunc(gens, threshold)
print win.error

0.218985969275
CPU times: user 4min 42s, sys: 6.67 s, total: 4min 49s
Wall time: 1min 14s


In [13]:
oresults = [playgame(oneturnai2(),win,newboard())*-1 for i in xrange(500)]
xresults = [playgame(win,oneturnai2(),newboard()) for i in xrange(500)]
results = array(oresults+xresults)
print 'lose', np.sum(results==-1)
print 'draw', np.sum(results==0)
print 'win', np.sum(results==1)
print 'mistake', np.sum(results==-2)

lose 638
draw 356
win 6
mistake 0


In [14]:
hidden = XOHidden.initalize(27,[300],9,activation=rectified_linear, endactivation=linear)
hlearnfunc = LayeredLearning(equalinputs, equalgoal, hidden)

In [15]:
%%time
for x in xrange(5):
    for i in xrange(10):
        hlearnfunc.frontlearn()
    for i in xrange(10):
        hlearnfunc.backlearn()


CPU times: user 41.8 s, sys: 945 ms, total: 42.7 s
Wall time: 17.2 s


In [16]:
equalhidden = hlearnfunc.genome
equalhidden.multi = 50
oresults = [playgame(oneturnai2(),equalhidden,newboard())*-1 for i in xrange(500)]
xresults = [playgame(equalhidden,oneturnai2(),newboard()) for i in xrange(500)]
results = array(oresults+xresults)
print 'lose', np.sum(results==-1)
print 'draw', np.sum(results==0)
print 'win', np.sum(results==1)
print 'mistake', np.sum(results==-2)

lose 66
draw 809
win 125
mistake 0


In [260]:
hidden = XOHidden.initalize(27,[300],9,activation=rectified_linear, endactivation=linear)
hlearnfunc = LayeredLearning(blockinputs, blockgoal, hidden)

In [261]:
%%time
for x in xrange(5):
    for i in xrange(10):
        hlearnfunc.frontlearn()
    for i in xrange(10):
        hlearnfunc.backlearn()

CPU times: user 39 s, sys: 380 ms, total: 39.4 s
Wall time: 15.7 s


In [19]:
blockhidden = hlearnfunc.genome
blockhidden.multi = 50


oresults = [playgame(oneturnai2(),blockhidden,newboard())*-1 for i in xrange(500)]
xresults = [playgame(blockhidden,oneturnai2(),newboard()) for i in xrange(500)]
results = array(oresults+xresults)
print 'lose', np.sum(results==-1)
print 'draw', np.sum(results==0)
print 'win', np.sum(results==1)
print 'mistake', np.sum(results==-2)

lose 42
draw 912
win 46
mistake 0


In [20]:
hidden = XOHidden.initalize(27,[300],9,activation=rectified_linear, endactivation=linear)
hlearnfunc = LayeredLearning(wininputs, wingoal, hidden)

In [21]:
%%time
for x in xrange(5):
    for i in xrange(10):
        hlearnfunc.frontlearn()
    for i in xrange(10):
        hlearnfunc.backlearn()

CPU times: user 41 s, sys: 892 ms, total: 41.9 s
Wall time: 17.1 s


In [263]:
winhidden = hlearnfunc.genome
winhidden.multi = 50


oresults = [playgame(oneturnai2(),winhidden,newboard())*-1 for i in xrange(500)]
xresults = [playgame(winhidden,oneturnai2(),newboard()) for i in xrange(500)]
results = array(oresults+xresults)
print 'lose', np.sum(results==-1)
print 'draw', np.sum(results==0)
print 'win', np.sum(results==1)
print 'mistake', np.sum(results==-2)

lose 33
draw 862
win 105
mistake 0


In [257]:
azure = XOQLearning()



In [258]:
%%time
for x in xrange(5):
    for i in xrange(10000):
        azure.learn(azure,'x', multi=2)
        azure.learn(azure,'o', multi=2)
    azure.multi = 50
    oresults = [playgame(oneturnai2(),azure,newboard())*-1 for i in xrange(500)]
    xresults = [playgame(azure,oneturnai2(),newboard()) for i in xrange(500)]
    results = array(oresults+xresults)
    print 'lose', np.sum(results==-1)
    print 'draw', np.sum(results==0)
    print 'win', np.sum(results==1)
    print 'mistake', np.sum(results==-2)



lose 196
draw 629
win 175
mistake 0
lose 68
draw 625
win 307
mistake 0
lose 14
draw 725
win 261
mistake 0
lose 6
draw 718
win 276
mistake 0
lose 0
draw 722
win 278
mistake 0
CPU times: user 33.3 s, sys: 151 ms, total: 33.4 s
Wall time: 33.4 s


In [ ]:
#Round Robin
a.multi = 50
azure.multi = 50
winhidden.multi = 50
blockhidden.multi = 50
equalhidden.multi = 50
qhidden.multi = 50


def calcWLD(ai1, ai2):
    oresults = [playgame(ai2,ai1,newboard())*-1 for i in xrange(500)]
    xresults = [playgame(ai1,ai2,newboard()) for i in xrange(500)]
    results = array(oresults+xresults)
    lose = np.sum(results==-1)
    draw = np.sum(results==0)
    win = np.sum(results==1)
    mistake = np.sum(results==-2)
    ai1WLD = win - lose
    ai2WLD = ai1WLD * -1
    return ai1WLD, ai2WLD

ais = [a, azure, equal, block, win, equalhidden, blockhidden, winhidden, oneturnai2(), stupidai2]
WLD = np.array([[0 for x in range(len(ais))] for i in range(len(ais))])
print WLD
for ai1 in range(len(ais)):
    for ai2 in range(ai1+1,len(ais)):
        if ai1 != ai2:
            ai1WLD, ai2WLD = calcWLD(ais[ai1], ais[ai2])
            WLD[ai1][ai2] = ai1WLD
            WLD[ai2][ai1] = ai2WLD

print WLD
# print calcWLD(a,winhidden) 

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [38]:
oresults = [playgame(winhidden,a,newboard())*-1 for i in xrange(500)]
xresults = [playgame(a,winhidden,newboard()) for i in xrange(500)]
results = array(oresults+xresults)
print 'lose', np.sum(results==-1)
print 'draw', np.sum(results==0)
print 'win', np.sum(results==1)
print 'mistake', np.sum(results==-2)
results = array(xresults)
print 'xlose', np.sum(results==-1)
print 'xdraw', np.sum(results==0)
print 'xwin', np.sum(results==1)
print 'xmistake', np.sum(results==-2)
results = array(oresults)
print 'olose', np.sum(results==-1)
print 'odraw', np.sum(results==0)
print 'owin', np.sum(results==1)
print 'omistake', np.sum(results==-2)

lose 0
draw 950
win 50
mistake 0
xlose 0
xdraw 450
xwin 50
xmistake 0
olose 0
odraw 500
owin 0
omistake 0


In [44]:
def transboard(inputs,side):
    oside = 'x' if side == 'o' else 'o'
    side = [1 if bit == side else 0 for bit in inputs] 
    oside = [1 if bit == oside else 0 for bit in inputs]
    space = [1 if bit == '.' else 0 for bit in inputs]
    return np.array(side + oside + space)

def goalin(data, movevalue, side):
    inputs = [board for board, move in data]
    goal = np.array([[movevalue-0.5 if i == move else 0 for i in range(9)] for board, move in data])
    goal += np.array([[0.5 if bit == '.' else 0 for bit in input] for input in inputs])
    inputs = [transboard(input, side) for input in inputs]
    return inputs, goal

In [23]:
xcoach = oneturnai2()
ocoach = oneturnai2()

for i in xrange(1000):
    playgame(xcoach, stupidai2, newboard())
    playgame(stupidai2, ocoach, newboard())
for i in xrange(5000):
    playgame(xcoach, oneturnai2(), newboard())
    playgame(oneturnai2(), ocoach, newboard())

xwindata = xcoach.windata.items()
xblockdata = xcoach.blockdata.items()
owindata = ocoach.windata.items()
oblockdata = ocoach.blockdata.items()

In [32]:
xwinin, xwingoal = goalin(xwindata, 1.0, 'x')
xblockin, xblockgoal = goalin(xblockdata, 1.0, 'x')

xinputs = [list(input) for input in xwinin] + [list(input) for input in xblockin]
xgoal = [list(goal) for goal in xwingoal] + [list(goal) for goal in xblockgoal]

owinin, owingoal = goalin(owindata, 1.0, 'o')
oblockin, oblockgoal = goalin(oblockdata, 1.0, 'o')

oinputs = [list(input) for input in owinin] + [list(input) for input in oblockin]
ogoal = [list(goal) for goal in owingoal] + [list(goal) for goal in oblockgoal]

inputs = oinputs+xinputs
goal = ogoal+xgoal

In [33]:
print inputs
print goal

[[0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0], [1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0], [1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0], [1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0], [0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1], [1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0], [1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1], [1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0], [0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1], [1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0], [0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0], [0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0], [0,

oxo..xxxo
[1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0]
[0.0, 0.0, 0.0, 0.5, 1.5, 0.0, 0.0, 0.0, 0.0]

In [48]:
%%time 
#Q-Learning, Reinforcement Learning.
for i in xrange(2000):
    azure.learn(azure,'x', multi=0.2)
    azure.learn(azure,'o', multi=0.2)
    
for i in xrange(100000):
    azure.learn(azure,'x', multi=0.2)
    azure.learn(azure,'o', multi=0.2)
    
oresults = [playgame(oneturnai2(),azure,newboard())*-1 for i in xrange(500)]
xresults = [playgame(azure,oneturnai2(),newboard()) for i in xrange(500)]
results = array(oresults+xresults)
print 'lose', np.sum(results==-1)
print 'draw', np.sum(results==0)
print 'win', np.sum(results==1)
print 'mistake', np.sum(results==-2)
for i in xrange(100000):
    azure.learn(azure,'x', multi=1)
    azure.learn(azure,'o', multi=1)
    
oresults = [playgame(oneturnai2(),azure,newboard())*-1 for i in xrange(500)]
xresults = [playgame(azure,oneturnai2(),newboard()) for i in xrange(500)]
results = array(oresults+xresults)
print 'lose', np.sum(results==-1)
print 'draw', np.sum(results==0)
print 'win', np.sum(results==1)
print 'mistake', np.sum(results==-2)
for i in xrange(100000):
    azure.learn(azure,'x', multi=5)
    azure.learn(azure,'o', multi=5)

oresults = [playgame(oneturnai2(),azure,newboard())*-1 for i in xrange(500)]
xresults = [playgame(azure,oneturnai2(),newboard()) for i in xrange(500)]
results = array(oresults+xresults)
print 'lose', np.sum(results==-1)
print 'draw', np.sum(results==0)
print 'win', np.sum(results==1)
print 'mistake', np.sum(results==-2)


KeyboardInterrupt: 

In [85]:
azure.multi = 7
oresults = [playgame(oneturnai2(),azure,newboard())*-1 for i in xrange(500)]
xresults = [playgame(azure,oneturnai2(),newboard()) for i in xrange(500)]
results = array(oresults+xresults)
print 'lose', np.sum(results==-1)
print 'draw', np.sum(results==0)
print 'win', np.sum(results==1)
print 'mistake', np.sum(results==-2)

lose 70
draw 557
win 373
mistake 0


In [83]:
for i in xrange(3): playgame(azure,azure,newboard(), see=True)

...
..x
...
-----
o..
..x
...
-----
o.x
..x
...
-----
o.x
..x
..o
-----
o.x
.xx
..o
-----
o.x
oxx
..o
-----
o.x
oxx
x.o
-----
x won
x..
...
...
-----
x..
.o.
...
-----
x..
xo.
...
-----
x..
xo.
o..
-----
x.x
xo.
o..
-----
xox
xo.
o..
-----
xox
xo.
ox.
-----
xox
xoo
ox.
-----
xox
xoo
oxx
-----
draw
..x
...
...
-----
..x
.o.
...
-----
x.x
.o.
...
-----
xox
.o.
...
-----
xox
.o.
.x.
-----
xox
.oo
.x.
-----
xox
xoo
.x.
-----
xox
xoo
ox.
-----
xox
xoo
oxx
-----
draw


In [42]:
goal = np.array(qtrain.goal)+1.0
print [list(bit) for bit in goal]

[[1.5, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0], [0.0, 0.0, 1.5, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0], [0.0, 1.5, 0.0, 0.0, 1.0, 1.0, 1.5, 1.6666666666666665, 0.0], [1.5, 0.0, 0.0, 0.5, 0.0, 0.5, 0.0, 1.0, 1.5], [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.5], [0.0, 1.0, 0.0, 0.0, 1.5, 0.0, 0.0, 0.0, 1.0], [0.0, 0.0, 1.0, 0.0, 0.0, 0.33333333333333337, 1.0, 1.0, 0.0], [1.0, 1.0, 0.5, 0.0, 0.0, 0.5, 0.0, 0.0, 1.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.9965753424657535, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.9910714285714286, 0.0, 1.0], [0.038461538461538436, 0.0, 0.030303030303030276, 0.0, 0.0, 0.0, 0.0, 0.89947089947089953, 0.033333333333333326], [0.0, 1.0, 0.0, 1.0, 1.5, 0.0, 1.5, 0.0, 0.5], [0.034482758620689613, 0.038461538461538436, 0.0, 0.0, 0.034482758620689613, 0.0, 0.0, 0.023809523809523836, 0.0], [0.0, 0.0, 0.0, 1.0, 0.0, 0.038961038961038974, 0.0, 0.013698630136986356, 0.017241379310344862], [0.0, 0.0, 1.0, 1.0, 1.0, 1.5, 0.0, 0.0, 1.5], [1.7819732034104749, 0.79470198675496695, 0.029

In [38]:
print qtrain.inputs

[[0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1], [0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1], [1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0], [0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1], [1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1], [0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1], [1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0], [0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1], [0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0], [0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1], [0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1], [1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1], [0,

In [110]:
class XOQHidden(XOHidden):
    def findmove(self, moves):
        y = rectified_linear(np.exp(moves*self.multi)-np.exp(self.offset*self.multi))
        s = np.sum(y)
        prob = y / s
        c = np.cumsum(prob)
        move = np.sum([c < np.random.random()])
        return move


In [111]:
hidden = XOQHidden.initalize(27,[300],9,activation=rectified_linear, endactivation=linear)
hlearnfunc = LayeredLearning(qtrain.inputs, np.array(qtrain.goal)+1.5, hidden)

In [114]:
%%time
for i in xrange(10):
    hlearnfunc.frontlearn()
    print i,qhidden.calcerror(qtrain.inputs,np.array(qtrain.goal)+1.5)

0 0.316036028701
1 0.316036028701
2 0.316036028701
3 0.316036028701
4 0.316036028701
5 0.316036028701
6 0.316036028701
7 0.316036028701
8 0.316036028701
9 0.316036028701
CPU times: user 8.48 s, sys: 121 ms, total: 8.6 s
Wall time: 2.17 s


In [115]:
%%time
for i in xrange(10):
    hlearnfunc.backlearn()
    print i,qhidden.calcerror(qtrain.inputs,np.array(qtrain.goal)+1.5)

0 0.316036028701
1 0.316036028701
2 0.316036028701
3 0.316036028701
4 0.316036028701
5 0.316036028701
6 0.316036028701
7 0.316036028701
8 0.316036028701
9 0.316036028701
CPU times: user 10.1 s, sys: 192 ms, total: 10.3 s
Wall time: 3.01 s


In [245]:
qhidden = hlearnfunc.genome
print qhidden.calcerror(qtrain.inputs,np.array(qtrain.goal)+1.4555555555555555555555)
qhidden.offset = 0
qhidden.multi = 150
oresults = [playgame(a,qhidden,newboard())*-1 for i in xrange(500)]
xresults = [playgame(qhidden,a,newboard()) for i in xrange(500)]
results = array(oresults+xresults)
print 'lose', np.sum(results==-1)
print 'draw', np.sum(results==0)
print 'win', np.sum(results==1)
print 'mistake', np.sum(results==-2)
print oresults

0.305825891601
lose 500
draw 500
win 0
mistake 0
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1

In [ ]:
# print np.array(qtrain.goal)+1.0

In [233]:
playgame(oneturnai2(),qhidden,newboard(), see=True)

.x.
...
...
-----
.x.
.o.
...
-----
.x.
.o.
.x.
-----
.xo
.o.
.x.
-----
.xo
.o.
xx.
-----
.xo
.o.
xxo
-----
.xo
.ox
xxo
-----
oxo
.ox
xxo
-----
o won


-1

In [253]:
print len(a.database)
print len(azure.database)

4238
4520
