In [1]:
from __future__ import division
from numpy.random import random, randint
from random import choice
import numpy as np
from numpy import dot, array
from neuralnet2 import *

In [2]:
def myinout():
    into = [randint(0,2),randint(0,2)]
    if into == [1,0] or into == [0,1]:# or into == [1,1]:
        outof = 1
    else:
        outof = -1
    return [into,outof]
ingoal = np.array([myinout() for i in range(20)]).T
print ingoal
inputs = np.array([i for i in ingoal[0]])
print inputs
goal = np.array([i for i in ingoal[1]])
print goal

[[[1, 1] [0, 0] [1, 1] [1, 0] [0, 0] [0, 0] [1, 0] [0, 0] [1, 0] [1, 1]
  [1, 0] [0, 0] [0, 1] [0, 1] [1, 0] [1, 1] [0, 1] [1, 1] [1, 1] [1, 0]]
 [-1 -1 -1 1 -1 -1 1 -1 1 -1 1 -1 1 1 1 -1 1 -1 -1 1]]
[[1 1]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [1 0]
 [1 1]
 [1 0]
 [0 0]
 [0 1]
 [0 1]
 [1 0]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [1 0]]
[-1 -1 -1  1 -1 -1  1 -1  1 -1  1 -1  1  1  1 -1  1 -1 -1  1]


In [3]:
a = Hidden.initalize(2,[300],1,activation=fast_sigmoid)
ta = LayeredLearning(inputs,goal,a)

In [4]:
%%time
for d in range(50):
    for i in range(5):
        ta.frontlearn()
    for i in range(5):
        ta.backlearn()
    print ta.genome.calcerror([[1,1],[1,0],[0,1],[0,0]],[-1,1,1,-1])

1.05009687133
1.05940070293
1.05768858964
1.05485907416
1.05377286924
1.05419252669
1.0561959166
1.05847461222
1.06037635578
1.06236211848
1.06453295862
1.0663449993
1.06791935722
1.0695081849
1.07078795052
1.07199379922
1.0731237632
1.07433444093
1.0753297537
1.07627843716
1.07727538768
1.0783156122
1.07928246482
1.08016867199
1.08103390124
1.08186560181
1.08254255807
1.08315679667
1.08369878464
1.08440026536
1.08514745511
1.08602089319
1.08690595737
1.08788764468
1.08900236975
1.09019348902
1.09142940922
1.0926068965
1.09378119386
1.09487495461
1.0959987768
1.09707956859
1.0980859687
1.0989609602
1.09999968332
1.10101309038
1.10198626114
1.10294038819
1.10383844885
1.10457385294
CPU times: user 445 ms, sys: 4.9 ms, total: 450 ms
Wall time: 448 ms


In [5]:
an = ta.genome
print an.calcout([[1,1],[1,0],[0,1],[0,0]])

[[-0.54994666]
 [ 0.59043548]
 [ 0.25728733]
 [-0.40383342]]


In [6]:
pop = [Hidden.initalize(2,[5],1) for i in range(100)]
popt = GeneticEvolution(inputs,goal,pop,50)

In [13]:
a = popt(100,0.02)
a.calcout([[1,1],[1,0],[0,1],[0,0]])#,[-1,1,1,-1])

Hidden(layers=[Perceptron(matrix=array([[-0.05195971,  0.24433889, -0.38285213,  0.15386748, -0.13524662],
       [-0.62653877,  0.22590078, -0.38610537,  0.01902992, -0.35895478]]), offset=array([[ 0.64475488,  0.48045031,  0.85400775,  0.66773919,  0.04624674]]), activation=<function rectified_linear at 0x10bbdcf50>, maxdelta=-0.106315598724), Perceptron(matrix=array([[ 0.05349421],
       [-0.48099332],
       [-0.36658286],
       [-0.14741931],
       [-0.06274907]]), offset=array([[ 0.5]]), activation=<function fast_sigmoid at 0x10bbdce60>, maxdelta=-0.415059725723)])
[[-0.09970409]]
1
0.994987619232


array([[-0.10102627],
       [-0.09970409],
       [-0.10035028],
       [-0.0999156 ]])